### ISSUE TITLE
tests: add a test to check all the validations are valid JSON

### ISSUE THREAD

**Issue by fromanirh** [kubevirt/common-templates#115]
the templates should ensure their validation annotation is syntactically valid, hence it is valid JSON.
Something like this could be enough (python like pseudocode):

```python
for tmpl in all(templates):
     validations = tmpl.annotations[TEMPLATE_VALIDATION]
    if not json.is_valid(validations):
       fail()
succeed()
```

**Comment by ksimon1** [comment]
I was thinking about this as well. Maybe i can insert this check to e2e tests which we have now
