### ISSUE TITLE
Windows templates show warning for SATA Disks

### ISSUE THREAD

**Issue by glekner** [kubevirt/common-templates#137]
Bugzilla - https://bugzilla.redhat.com/show_bug.cgi?id=1803756

Newly created Windows VMs don't have VirtIO drivers, so the guest tools CD should be SATA in order to install them, therefore we should remove the SATA warning.

Possible place to fix -
https://github.com/kubevirt/common-templates/blob/5633ef8542565fcf80959a6ce5e048114ed1aa1d/templates/windows.tpl.yaml#L48

**Comment by MarSik** [comment]
Actually, I would change the matching part above it to only check disks and ignore cdroms.

`"path": "jsonpath::.spec.domain.devices.disks[*].disk.bus",`
