### ISSUE TITLE
Wrong display name for Centos 7 templates

### ISSUE THREAD

**Issue by irosenzw** [kubevirt/common-templates#145]
Centos 7 display name should be:
```
name.os.template.kubevirt.io/centos7.0: CentOS 7.0 or higher VM
```
but instead it is:
```
name.os.template.kubevirt.io/centos7.0: CentOS 7 or higher VM
```

It is important since operating systems dropdown at the UI is inconsistent:
![Screenshot from 2020-04-16 12-58-33](https://user-images.githubusercontent.com/18301938/79443089-0f0bf600-7fe2-11ea-8ffe-239921059d87.png)

**Comment by MarSik** [comment]
You will have to file a bug in osinfo-db. The data comes from there: https://gitlab.com/libosinfo/osinfo-db/-/blob/master/data/os/centos.org/centos-7.0.xml.in#L7

I do not think a local override is the right way to go.

**Comment by MarSik** [comment]
Actually, the "or higher" is not valid for CentOS 7. There were no minor releases for that os. See https://wiki.centos.org/FAQ/General FAQ 23 item 3)

**Comment by irosenzw** [comment]
> You will have to file a bug in osinfo-db. The data comes from there: https://gitlab.com/libosinfo/osinfo-db/-/blob/master/data/os/centos.org/centos-7.0.xml.in#L7
> 
> I do not think a local override is the right way to go.

@MarSik So how do you explain we see "Centos 8.0" although in osinfo-db it is written "Centos 8"?:
[https://gitlab.com/libosinfo/osinfo-db/-/blob/master/data/os/centos.org/centos-8.xml.in#L6](https://gitlab.com/libosinfo/osinfo-db/-/blob/master/data/os/centos.org/centos-8.xml.in#L6)

**Comment by ksimon1** [comment]
This "Centos 8.0" name comes from https://github.com/kubevirt/common-templates/blob/master/osinfo-db-override/os/centos.org/centos-8.0.xml. This file overrides data in osinfo-db. We can delete this file and keep data from osinfo-db. Then it will report:
```centos 6.0
centos 7
centos 8```
