### ISSUE TITLE
linux template always sets networkInterfaceMultiqueue: true, but this currently requires virtio-net

### ISSUE THREAD

**Issue by maya-r** [kubevirt/common-templates#186]
/kind bug

**What happened**:
Tried to use a linux template in CNV.
Changed the network interface (long story for why I wanted to do this, but that is besides the point) to rtl8139 or something.
I couldn't create the resulting VM, I got a [validation error:](https://github.com/kubevirt/kubevirt/blob/master/pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter.go#L784-L791)
"virtio-net multiqueue request, but there are no virtio interfaces defined".

**Comment by fdupont-redhat** [comment]
This also affects virtual machines without network interfaces. I agree it's a weird use case, but it can happen to have an isolated system that only manipulates data on a RWX persistent volume shared with other pods.
