### ISSUE TITLE
Sign-off commits when creating a new PR to ssp-operator

### ISSUE THREAD

**Issue by vatsalparekh** [kubevirt/common-templates#238]
https://github.com/kubevirt/common-templates/blob/db7a44e5bd79c1ff48561650b0d4ea2dfe8ecad9/travis_ci/release-templates-ssp-operator.sh#L46

**Comment by omeryahud** [comment]
Nice catch, do you think simply changing it to `-sm` would do the trick?

**Comment by vatsalparekh** [comment]
@omeryahud I think it should
