### ISSUE TITLE
follow libosinfo automatically

### ISSUE THREAD

**Issue by dankenigsberg** [kubevirt/common-templates#285]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind enhancement

Idea (low priority, as libosinfo releases are not that common):
- have a script that pulls the latest tag from [libosinfo](https://gitlab.com/libosinfo/libosinfo/-/tree/master/osinfo) and keep us up to date
- have this run automatically (Prow?) when a new version is out

**Comment by MarSik** [comment]
This is actually not that hard. The directory is a git submodule, so it is just a matter of running git pull --rebase from the osinfo-db dir and either merging that directly or generating PR when the HEAD changed. Running this periodically should be totally fine.

The other option is to drop the submodule and always check out the latest version during the build (less reproducible though).

**Comment by fidencio** [comment]
@dankenigsberg, @MarSik,

Hey! osinfo maintainer here! Are you guys familiar with `osinfo-db-import` (part of osinfo-db-tools package)? 

Let's say you want to have the latest osinfo-db as part of `/tmp/osinfo`, what you'd need to do is simply calling: `osinfo-db-import --latest --dir /tmp/osinfo`.

That would solve the issue for you guys and that's the recommended way to update osinfo-db.

Anyways, if you guys can give me a pointer, I'd be happy to provide patches for this.

**Comment by MarSik** [comment]
The import requires that you actually have osinfo-db installed, it also does not allow you to track which osinfo-db version was used for which git release.

**Comment by fidencio** [comment]
> The import requires that you actually have osinfo-db installed.

@MarSik, what do you mean?
osinfo-db-tools doesn't actually depend on osinfo-db.
```
========================================================================================================================================
 Package                                      Architecture            Version                             Repository               Size
========================================================================================================================================
Installing:
 osinfo-db-tools                              x86_64                  1.8.0-2.fc33                        fedora                   66 k
Installing dependencies:
 fonts-filesystem                             noarch                  1:2.0.5-4.fc33                      fedora                  8.7 k
 glib-networking                              x86_64                  2.66.0-1.fc33                       fedora                  161 k
 gsettings-desktop-schemas                    x86_64                  3.38.0-1.fc33                       fedora                  681 k
 json-glib                                    x86_64                  1.6.0-1.fc33                        fedora                  149 k
 libmodman                                    x86_64                  2.0.1-23.fc33                       fedora                   33 k
 libproxy                                     x86_64                  0.4.15-25.fc33                      fedora                   65 k
 libsoup                                      x86_64                  2.72.0-3.fc33                       fedora                  398 k
Installing weak dependencies:
 abattis-cantarell-fonts                      noarch                  0.201-4.fc33                        fedora                  335 k
 adobe-source-code-pro-fonts                  noarch                  2.030.1.050-9.fc33                  fedora                  834 k

Transaction Summary
========================================================================================================================================
Install  10 Packages

```

> it also does not allow you to track which osinfo-db version was used for which git release.

Using `--latest` gives you the latest official release. Wherever this release is installed, it'll contain a VERSION file indicating the release.

**Comment by fidencio** [comment]
Oh, but now I think I got what you meant, @MarSik.
It's simply easier to run a custom `git reset --hard $(git describe --abbrev=0)` as part of some script than actually using osinfo-db-tools. If that's what you mean, yep, I agree. :-).

**Comment by MarSik** [comment]
Yes, that is exactly it. You get the right sources just by checking out the git repository and initializing submodules.
