### ISSUE TITLE
Deployment to the SSP Operator fails

### ISSUE THREAD

**Issue by kwiesmueller** [kubevirt/common-templates#293]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

It seems like travis can no longer push the deployment to the ssp-operator repository:
https://travis-ci.com/github/kubevirt/common-templates/builds/207709874#L2963

**What you expected to happen**:
The build to deploy.

**How to reproduce it (as minimally and precisely as possible)**:
Run travis-ci.

**Comment by akrejcir** [comment]
@vatsalparekh, Is this solved?

/remove-lifecycle rotten

**Comment by akrejcir** [comment]
The last PR that updated the templates was 4. May, so the automation works.
https://github.com/kubevirt/ssp-operator/pull/163

/close
