### ISSUE TITLE
periodic-common-templates-nightly-image-builder is failing

### ISSUE THREAD

**Issue by maya-r** [kubevirt/common-templates#335]
/kind bug
/triage build-watcher

FYI, if you haven't noticed, this build seems to be related and failing for 
https://prow.apps.ovirt.org/?type=periodic&job=periodic-common-templates-nightly-image-builder

**Comment by omeryahud** [comment]
Thanks @maya-r 
/assign @shwetaap Shweta, please take a look, and if this is failing because of your pending PR, please make sure to update this issue once it is resolved

**Comment by shwetaap** [comment]
Added the fix in this PR - https://github.com/kubevirt/project-infra/pull/1029
