### ISSUE TITLE
Proposal to archive this repo 

### ISSUE THREAD

**Issue by mazzystr** [kubevirt/common-templates#349]
Since templates is a Red Hat OpenShift feature I propose we archive this repo.

This data should be served or pkg'd by Red Hat OpenShift Virtualization NOT served from the community project.

@fabiand @davidvossel

**Comment by davidvossel** [comment]
Unless we plan to pivot to using helm charts, or another community friendly templating standard, I could consider moving this to the https://github.com/openshift org.

**Comment by mazzystr** [comment]
Moving the templates to openShift GitHub org is +1 from me
