### ISSUE TITLE
Create Template for win2k22

### ISSUE THREAD

**Issue by therevoman** [kubevirt/common-templates#479]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug
/kind enhancement

**What happened**:
Went to create a virtual machine from Windows 2022.  There was no catalog item or template for it.  Not a big deal but customers will ask.

**What you expected to happen**:
I expected to find a Catalog item and Template for Win2k22

**How to reproduce it (as minimally and precisely as possible)**:
View Virtualization -> Template or Virtualization -> Catalog

**Anything else we need to know?**:

**Environment**:
OpenShift 4.11.4

**Comment by ksimon1** [comment]
Hi, this is fixed by https://github.com/kubevirt/common-templates/pull/475. It will be released probably next week
